name: CI Workflow for Job Search Microservice

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run Unit Tests
    - name: Run Tests
      run: |
        pytest tests/ --maxfail=5 --disable-warnings

    # Step 5: Lint and Format Code
    - name: Check Code Style with Flake8
      run: |
        pip install flake8
        flake8 app/

    # Step 6: Run the Microservice for Testing
    - name: Run the Microservice
      run: |
        nohup uvicorn app.main:app --host 127.0.0.1 --port 8080 &
        sleep 5  # Allow time for the app to start

    # Step 7: Test Endpoints with cURL
    - name: Test Endpoints
      run: |
        curl -X GET http://127.0.0.1:8080/ | grep "Welcome"
        curl -X GET http://127.0.0.1:8080/docs | grep "openapi"

