name: CI/CD Pipeline for Job Search Microservice

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual runs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Install Dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Deploy to EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Navigate to the app directory (adjust as needed)
          cd /home/${{ secrets.EC2_USER }}/job-search-service || mkdir /home/${{ secrets.EC2_USER }}/job-search-service && cd /home/${{ secrets.EC2_USER }}/job-search-service

          # Pull the latest code
          git init
          git remote add origin https://github.com/C1araYu/stayemployed-job-search-service.git || true
          git fetch origin
          git reset --hard origin/main

          # Set up Python environment
          python3 -m venv venv || true
          source venv/bin/activate
          pip install --no-cache-dir -r requirements.txt

          # Kill any existing uvicorn processes
          pkill -f "uvicorn app.main:app" || true

          # Start the app in the background
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload > app.log 2>&1 &
